overrides:
  better-call: 1.3.5

allowBuilds:
  '@prisma/client': true
  better-sqlite3: true
  esbuild: true
minimumReleaseAgeExclude:
  - '@ai-sdk/openai@3.0.67'
  - '@better-auth/core@1.6.12'
  - '@better-auth/drizzle-adapter@1.6.12'
  - '@better-auth/kysely-adapter@1.6.12'
  - '@better-auth/memory-adapter@1.6.12'
  - '@better-auth/mongo-adapter@1.6.12'
  - '@better-auth/prisma-adapter@1.6.12'
  - '@better-auth/telemetry@1.6.12'
  - '@eslint/plugin-kit@0.7.2'
  - ai@6.0.193
  - better-auth@1.6.12
  - eslint@10.4.1
  - svelte@5.56.0
  - '@ai-sdk/gateway@3.0.124'
  - '@sveltejs/kit@2.63.0'
  - '@sveltejs/load-config@0.1.1'
  - ai@6.0.196
  - pixi.js@8.19.0
  - svelte-check@4.6.0
